@startuml
class Player {
    -Map<int, Dice> boardDices
    -Map<int, Dice> keptDices
    -PlayerScore score
    --
    rollBoardDices()
    keepDice(int index)
    replayDice(int index)
    ==
    0 <= boardDices.size() <= 5
    0 <= keptDices.size() <= 5
    keptDices.size() + boardDices.size() == 5
}

class PlayerScore {

    --
    save(Set<Dice> dices)
}

class Dice {
    Integer value
    --
    roll()
    ==
    1 <= value <= 6
}

class Game

Player *-- Dice

@enduml