@startuml
class Player {
    -Set<YathzeeDice> dices
    -PlayerScore score
    --
    +void rollBoardDices()
    +void keepDice(int index)
    +void replayDice(int index)
    +Map<int, bool> displayDices()
    ==
    dices.size() == 5
}

class PlayerScore {

    --
    save(Set<Dice> dices)
}

class YathzeeScore {
    String name
    int baseScore
}

class YathzeeDice {
    -bool kept
    -int index
    +void keep()
    +void replay()
}

class Dice {
    -Integer value
    --
    #void roll()
    +Integer getValue()
    ==
    1 <= value <= 6
}

class Game

Player *-- YathzeeDice
Player *-- PlayerScore
YathzeeDice --|> Dice

@enduml